# Build settings
theme: minima
title: "Finlay McAlpine"
email: hello@finlaymcalpine.com
description: "Made with GitHub Pages & Jekyll"

linkedin_username: finlay-mcalpine
github_username:  finlaymcalpine

markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
